apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3fs-fuse
  labels:
    app: s3fs-fuse
spec:
  selector:
    matchLabels:
      app: s3fs-fuse
  template:
    metadata:
      labels:
        app: s3fs-fuse
    spec:
      containers:
        - name: s3fs-fuse
          image: {{ .Values.s3fsImage }}
          securityContext:
            privileged: true
          envFrom:
            # secrets need to contain: AWS_S3_ACCESS_KEY_ID, AWS_S3_BUCKET, AWS_S3_SECRET_ACCESS_KEY
            - secretRef:
                name: {{ .Values.secretsName }}
          volumeMounts:
            - name: {{ .Values.volumesFuseName }}
              mountPath: /dev/fuse
            - name: {{ .Values.volumesS3FsName }}
              mountPath: /opt/s3fs/bucket:rshared
      volumes:
        - name: {{ .Values.volumesFuseName }}
          hostPath:
            path: /dev/fuse
        - name: {{ .Values.volumesS3FsName }}
          hostPath:
            path: /mnt/s3data
