# TODO: because this is a common DaemonSet (namespace "default"),
#   is it right to put it in this chart?
# TODO: on AWS we could use IAM to get rid of the Secret used here,
#   i.e. pass a "pod itentity" to the pod.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3fs-fuse
  namespace: {{ .Values.namespace }}
  labels:
    app: s3fs-fuse
spec:
  selector:
    matchLabels:
      app: s3fs-fuse
  template:
    metadata:
      labels:
        app: s3fs-fuse
    spec:
      containers:
        - name: s3fs-fuse
          image: {{ .Values.s3fsImage }}
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                # TODO: put into values.yaml
                name: s3fs-fuse-secrets
          volumeMounts:
            - name: fuse-device
              mountPath: /dev/fuse
            - name: mnt-s3fs-bucket
              mountPath: /opt/s3fs/bucket:rshared
      volumes:
        - name: fuse-device
          hostPath:
            path: /dev/fuse
        - name: mnt-s3fs-bucket
          hostPath:
            path: /mnt/s3data


#            - name: AWS_S3_BUCKET
#              envFrom:
#                configMapKeyRef:
#                  name: s3fs-fuse
#                  key: S3_BUCKET
#            - name: AWS_S3_ACCESS_KEY_ID
#              valueFrom:
#                secretKeyRef:
#                  name: s3fs-fuse
#                  key: AWS_S3_ACCESS_KEY_ID
#            - name: AWS_S3_SECRET_ACCESS_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: s3fs-fuse
#                  key: AWS_S3_SECRET_ACCESS_KEY
