apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xcube-hub.fullname" . }}
  labels:
    {{- include "xcube-hub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xcube-hub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xcube-hub.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "xcube-hub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: {{ .Values.storeConfigMapName }}
          configMap:
            name: {{ .Values.storeConfigMapName }}
        {{ with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{ end }}
      initContainers:
        {{ with .Values.initContainers }}
        {{- toYaml .  | nindent 8 }}
        {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- with .Values.configMaps }}
            - configMapRef:
                name: {{ . }}
            {{ end }}
            {{- with .Values.hubSecrets }}
            - secretRef:
                name: {{ . }}
            {{ end }}
          env:
            {{- with .Values.cubegensSecrets }}
            - name: XCUBE_HUB_CUBEGENS_SECRET
              value: {{ . }}
            {{ end }}
            {{- with .Values.cubegensConfigMaps }}
            - name: XCUBE_HUB_CUBEGENS_MAP
              value: {{ . }}
            {{ end }}
            {{ toYaml .Values.envs | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{ if .Values.livenessReadinessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessReadinessProbe.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.apiPath }}
              port: http
          readinessProbe:
            initialDelaySeconds: {{ .Values.livenessReadinessProbe.initialDelaySeconds }}
            httpGet:
              path: {{ .Values.apiPath }}
              port: http
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.storeConfigMapName }}
              mountPath: "/etc/xcube-hub"
              readOnly: true
            {{ with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
